# -*- coding: utf-8 -*-
"""future_ml01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSUQuKYZpu341M8lLzFJLIMLgTVeRLnB
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_excel("/content/Online Retail.xlsx")

df.head(5)

df.info()

df.isnull().sum()

df.dropna()

df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

df=df[df['Quantity']>0]

df=df[df['UnitPrice']>0]

df['Sales'] = df['Quantity'] * df['UnitPrice']

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

daily_sales = df.groupby(df['InvoiceDate'].dt.date)['Sales'].sum().reset_index()

daily_sales.columns = ['Date','Sales']

plt.figure(figsize=(12,5))
plt.plot(daily_sales['Date'], daily_sales['Sales'])
plt.title("Daily Sales")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

daily_sales['Date'] = pd.to_datetime(daily_sales['Date'])

daily_sales['Year'] = daily_sales['Date'].dt.year
daily_sales['Month'] = daily_sales['Date'].dt.month
daily_sales['Day'] = daily_sales['Date'].dt.day
daily_sales['Weekday'] = daily_sales['Date'].dt.dayofweek

daily_sales = daily_sales.dropna()
daily_sales['Lag1'] = daily_sales['Sales'].shift(1)
daily_sales['Lag7'] = daily_sales['Sales'].shift(7)
daily_sales = daily_sales.dropna()

train = daily_sales[:-30]
test = daily_sales[-30:]

X_train = train[['Year', 'Month', 'Day', 'Weekday', 'Lag1', 'Lag7']]
y_train = train['Sales']

X_test = test[['Year', 'Month', 'Day', 'Weekday', 'Lag1', 'Lag7']]
y_test = test['Sales']

from sklearn.ensemble import RandomForestRegressor

model=(RandomForestRegressor
 (n_estimators=100,
  random_state=42))

model.fit(X_train, y_train)

predictions = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, predictions)

mse = mean_squared_error(y_test, predictions)

rmse = np.sqrt(mse)

print("MAE:", mae)
print("RMSE:", rmse)

results = pd.DataFrame({
    'Date': test['Date'],
    'Actual Sales': y_test,
    'Predicted Sales': predictions
})

results.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.plot(results['Date'], results['Actual Sales'], label='Actual')

plt.plot(results['Date'], results['Predicted Sales'], label='Predicted')

plt.title("Actual vs Predicted Sales")

plt.xlabel("Date")

plt.ylabel("Sales")

plt.legend()

plt.show()

results.to_csv("Forecast.csv", index=False)

